### ISSUE TITLE
Filter wizard raises errors in Python3

### ISSUE THREAD

**Issue by mpsonntag** [INM-6/python-odmltables#24]
The filter wizard still raises errors and is not properly usable when running odmltables with Python 3.

- [ ] version 0.2
- [x] version 1.0

**Comment by mpsonntag** [comment]
Here is the stacktrace to make the error easier to identify, sorry for not already including it in the first place...
```
Traceback (most recent call last):
  File "/home/msonntag/Chaos/software/mconda2/envs/ot3/lib/python3.5/site-packages/odmltables/gui/filterpages.py", line 470, in initializePage
    self.load_odml()
  File "/home/msonntag/Chaos/software/mconda2/envs/ot3/lib/python3.5/site-packages/odmltables/gui/filterpages.py", line 878, in load_odml
    self.update_tree(self.table)
  File "/home/msonntag/Chaos/software/mconda2/envs/ot3/lib/python3.5/site-packages/odmltables/gui/filterpages.py", line 888, in update_tree
    self.create_valuetree(self.odmltree, table)
  File "/home/msonntag/Chaos/software/mconda2/envs/ot3/lib/python3.5/site-packages/odmltables/gui/filterpages.py", line 958, in create_valuetree
    new_sec = Qtg.QTreeWidgetItem(parent_sec, [''] + val)
TypeError: arguments did not match any overloaded call:
  QTreeWidgetItem(type: int = QTreeWidgetItem.Type): argument 1 has unexpected type 'QTreeWidgetItem'
  QTreeWidgetItem(object, type: int = QTreeWidgetItem.Type): argument 1 has unexpected type 'QTreeWidgetItem'
  QTreeWidgetItem(QTreeWidget, type: int = QTreeWidgetItem.Type): argument 1 has unexpected type 'QTreeWidgetItem'
  QTreeWidgetItem(QTreeWidget, object, type: int = QTreeWidgetItem.Type): argument 1 has unexpected type 'QTreeWidgetItem'
  QTreeWidgetItem(QTreeWidget, QTreeWidgetItem, type: int = QTreeWidgetItem.Type): argument 1 has unexpected type 'QTreeWidgetItem'
  QTreeWidgetItem(QTreeWidgetItem, type: int = QTreeWidgetItem.Type): argument 2 has unexpected type 'list'
  QTreeWidgetItem(QTreeWidgetItem, object, type: int = QTreeWidgetItem.Type): argument 2 has unexpected type 'list'
  QTreeWidgetItem(QTreeWidgetItem, QTreeWidgetItem, type: int = QTreeWidgetItem.Type): argument 2 has unexpected type 'list'
  QTreeWidgetItem(QTreeWidgetItem): too many arguments
```

**Comment by JuliaSprenger** [comment]
- [x] version 0.2
- [ ] version 1.0

**Comment by JuliaSprenger** [comment]
#115
