### ISSUE TITLE
Unicode coding issue

### ISSUE THREAD

**Issue by mdenker** [INM-6/python-odmltables#4]
When selecting a certain file for filtering in the graphical GUI, it responds with
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2126' in position 1: ordinal not in range(128)

The output is
################### 2016-09-09 09:48:45.222483 ###################
Traceback (most recent call last):
  File "/home/denker/Projects/toolboxes/py/python-odmltables/odmltables/wizard/filterpages.py", line 449, in initializePage
    self.load_odml()
  File "/home/denker/Projects/toolboxes/py/python-odmltables/odmltables/wizard/filterpages.py", line 857, in load_odml
    self.update_tree(self.table)
  File "/home/denker/Projects/toolboxes/py/python-odmltables/odmltables/wizard/filterpages.py", line 867, in update_tree
    self.create_valuetree(self.odmltree, table)
  File "/home/denker/Projects/toolboxes/py/python-odmltables/odmltables/wizard/filterpages.py", line 936, in create_valuetree
    val = [str(v) for v in values[value]]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2126' in position 1: ordinal not in range(128)

################### 2016-09-09 10:11:45.073187 ###################
Traceback (most recent call last):
  File "/home/denker/Projects/toolboxes/py/python-odmltables/odmltables/wizard/filterpages.py", line 449, in initializePage
    self.load_odml()
  File "/home/denker/Projects/toolboxes/py/python-odmltables/odmltables/wizard/filterpages.py", line 857, in load_odml
    self.update_tree(self.table)
  File "/home/denker/Projects/toolboxes/py/python-odmltables/odmltables/wizard/filterpages.py", line 867, in update_tree
    self.create_valuetree(self.odmltree, table)
  File "/home/denker/Projects/toolboxes/py/python-odmltables/odmltables/wizard/filterpages.py", line 936, in create_valuetree
    val = [str(v) for v in values[value]]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2126' in position 1: ordinal not in range(128)

**Comment by mdenker** [comment]
Btw, this is the "ohm" character...

**Comment by mdenker** [comment]
Potentially test doing something like: str.encode('utf-8')

**Comment by mdenker** [comment]
Solved by using unicode method instead of str.
